#!/usr/bin/env sh
set -eu

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set ON_ERROR_STOP=1 <<-SQL
  CREATE ROLE "$APP_DATABASE_USER" LOGIN PASSWORD '$APP_DATABASE_PASSWORD';
  CREATE ROLE "$PROVIDER_DATABASE_USER" LOGIN PASSWORD '$PROVIDER_DATABASE_PASSWORD';
  CREATE DATABASE "$APP_DATABASE_NAME" OWNER "$APP_DATABASE_USER";
  CREATE DATABASE "$PROVIDER_DATABASE_NAME" OWNER "$PROVIDER_DATABASE_USER";
  REVOKE CONNECT ON DATABASE "$APP_DATABASE_NAME" FROM PUBLIC;
  REVOKE CONNECT ON DATABASE "$PROVIDER_DATABASE_NAME" FROM PUBLIC;
  GRANT CONNECT ON DATABASE "$APP_DATABASE_NAME" TO "$APP_DATABASE_USER";
  GRANT CONNECT ON DATABASE "$PROVIDER_DATABASE_NAME" TO "$PROVIDER_DATABASE_USER";
SQL
